### ISSUE TITLE
npm starts, and explodes

### ISSUE THREAD

**Issue by miguelgargallo** [creativesuraj/react-material-ui-login#2]
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/user/Apps/Not-Live/react-material-ui-login/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/user/Apps/Not-Live/react-material-ui-login/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/user/Apps/Not-Live/react-material-ui-login/node_modules/babel-loader/lib/index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

**Comment by creativesuraj** [comment]
which node version are you using?
